server:
  port: 80

spring:
  application:
    name: consumer-dept-80
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
